### ISSUE TITLE
V1 Alpha

### ISSUE THREAD

**Issue by versustunez** [versustunez/VeNoNex#12]
For the First Demo Alpha

# Todo

- [ ] GUI
   - [x] Matrix GUI
   - [ ] PresetManager
   - [x] Oscillator GUI
   - [x] LFO GUI (is like Oscillator GUI but a bit different!) (Missing LFO-Wave!)
   - [ ] FX-GUI

- [ ] Core
   - [x] Matrix Implementation
   - [x] Mono Legato
   - [x] Portamento
   - [x] Filter (OSC)
   - [ ] Wavetables
      - [ ] Roms
      - [ ] Special Effects
   - [ ] FX-Chain
      - [ ] Distortion
         - [ ] HardClipper
         - [ ] SoftClipper
         - [ ] Rectifier
         - [ ] Foldback
         - [ ] Some Own Weird without names
      - [ ] Filter
      - [ ] Slew Like Limiter (For Modulation stuff)
      - [ ] Dummy Compressor
      - [ ] 3Band EQ

- [ ] Optional
   - [ ] Reduce GPU-Calls
   - [ ] CPU-Optimisation
      - [ ] Caching of Parameters to avoid recalculation of "expensive" functions!
   - [ ] Cleanup
